'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import { ShieldCheck, Loader2 } from 'lucide-react'
import { toast } from 'sonner'

export default function MFAPage() {
  const supabase = createClient()
  const router = useRouter()
  const [code, setCode] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [factorId, setFactorId] = useState<string | null>(null)

  useEffect(() => {
    async function loadMfa() {
      const { data: factors, error } = await supabase.auth.mfa.listFactors()
      if (error) {
        toast.error('Failed to load MFA factors')
        return
      }

      const totpFactor = factors.totp[0]
      if (!totpFactor) {
        // No TOTP factor found, maybe they don't actually need MFA?
        // Redirect to dashboard just in case.
        router.push('/dashboard')
        return
      }
      
      setFactorId(totpFactor.id)
    }

    loadMfa()
  }, [supabase, router])

  async function handleVerify(e: React.FormEvent) {
    e.preventDefault()
    
    if (!factorId) {
      toast.error('No MFA factor found')
      return
    }

    if (code.length !== 6) {
      setError('Please enter a 6-digit code')
      return
    }

    setLoading(true)
    setError('')

    try {
      const { data, error } = await supabase.auth.mfa.challengeAndVerify({
        factorId,
        code
      })

      if (error) throw error
      
      // Successfully verified AAL2
      toast.success('Verification successful')
      window.location.href = '/dashboard'
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Invalid verification code')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="animated-bg min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-[#00E5CC]/20 mb-6">
            <ShieldCheck className="w-8 h-8 text-[#00E5CC]" />
          </div>
          <h1 className="text-2xl font-bold text-white">Two-Step Verification</h1>
          <p className="text-gray-400 text-sm mt-2">
            Enter the 6-digit authentication code generated by your authenticator app.
          </p>
        </div>

        <div className="glass rounded-2xl p-8 border border-white/5">
          <form onSubmit={handleVerify} className="space-y-6">
            <div>
              <label className="block text-xs text-gray-400 mb-2 font-medium text-center">
                Authentication Code
              </label>
              <input
                type="text"
                required
                value={code}
                onChange={(e) => {
                  setCode(e.target.value.replace(/\D/g, '').slice(0, 6))
                  setError('')
                }}
                placeholder="000000"
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-4 text-center text-white text-2xl tracking-[0.5em] font-mono placeholder-gray-600 focus:outline-none focus:border-[#00E5CC] transition-colors"
              />
            </div>

            {error && (
              <p className="text-sm text-red-400 text-center">{error}</p>
            )}

            <button
              type="submit" disabled={loading || code.length !== 6}
              className="w-full bg-[#00E5CC] hover:bg-[#00c2ad] disabled:opacity-60 text-[#0A0A0F] py-3 rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2 glow-teal"
            >
              {loading && <Loader2 className="w-4 h-4 animate-spin" />}
              Verify and Continue
            </button>
            
            <button
              type="button"
              onClick={() => {
                supabase.auth.signOut()
                router.push('/auth/login')
              }}
              className="w-full mt-2 text-sm text-gray-400 hover:text-white transition-colors"
            >
              Cancel and sign out
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}
