'use client'

import { Star } from 'lucide-react'
import { StaggerContainer, StaggerItem } from '@/components/animations'

const TESTIMONIALS = [
  {
    company: "Automotive Parts Manufacturer",
    quote: "Deploying PackIQ was the single biggest ROI decision we made this year. We saw a 92% reduction in defective units reaching assembly.",
    role: "Plant Manager",
    rating: 5
  },
  {
    company: "Global Beverage Corp",
    quote: "The speed of inference is what won us over. At 1,200 units per minute, traditional systems failed. PackIQ didn't miss a single breach.",
    role: "Head of QA",
    rating: 5
  },
  {
    company: "Pharma Logistics Group",
    quote: "The compliance reports generated by the AI are now our gold standard for BIS audits. Zero stress during our last three raids.",
    role: "Operations Director",
    rating: 5
  }
]

export function TestimonialsSection() {
  return (
    <section className="py-24 px-6 bg-white/[0.01]">
      <div className="max-w-[1200px] mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold font-syne mb-4">Trusted by Industry Leaders</h2>
          <p className="text-gray-500">Real impact on the world's most demanding production lines.</p>
        </div>

        <StaggerContainer className="grid md:grid-cols-3 gap-8">
          {TESTIMONIALS.map((t, i) => (
            <StaggerItem key={i}>
              <div className="p-10 bg-[#0A0A0F] border-l-4 border-[#00FFD1] rounded-2xl border-y border-r border-white/5 flex flex-col justify-between h-full">
                <div>
                  <div className="flex gap-1 mb-6">
                    {[...Array(t.rating)].map((_, j) => (
                      <Star key={j} className="w-4 h-4 fill-[#00FFD1] text-[#00FFD1]" />
                    ))}
                  </div>
                  <p className="text-lg text-gray-300 italic mb-8 leading-relaxed">"{t.quote}"</p>
                </div>
                
                <div>
                  <div className="text-sm font-bold text-white mb-1">{t.company}</div>
                  <div className="text-xs text-gray-500 uppercase tracking-widest">{t.role}</div>
                </div>
              </div>
            </StaggerItem>
          ))}
        </StaggerContainer>
      </div>
    </section>
  )
}
